kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.documentIntelligence.secret.name}}
data:
  apiKey: {{ .Values.documentIntelligence.secret.apiKeyValue | b64enc }}
  endpoint: {{ .Values.documentIntelligence.secret.endpointValue | b64enc }}
type: Opaque