apiVersion: v1
kind: ConfigMap
metadata:
  name: api-endpoints
data:
  LAYOUT_ENDPOINT: "https://{{ template  "api.layout.fqdn" .}}"
  READ_ENDPOINT: "https://{{ template "api.read.fqdn" .}}"
  INVOICE_ENDPOINT: "https://{{ template "api.invoice.fqdn" .}}"
  RECEIPT_ENDPOINT: "https://{{ template "api.receipt.fqdn" .}}"
  IDDOCUMENT_ENDPOINT: "https://{{ template "api.id.fqdn" .}}"
  CUSTOM_ENDPOINT: "https://{{ template "api.customtemplate.fqdn" .}}"
  OIDC_URL: "https://{{ template "oidc.fqdn" .}}/connect/token"
  SSL_VERIFY: "False"
  OIDC_CLIENT_SCOPE: "{{ .Values.oauth2proxy.scope }}"
  OIDC_CLIENT_AUDIENCE: "aiservices"
  