{{- if .Values.receipt.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-document-intelligence.receiptName" . }}
  labels: 
    {{- include "ai-document-intelligence.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "ai-document-intelligence.receiptName" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.receipt.port }}
      targetPort: {{ .Values.receipt.port }}
  selector:
    app.kubernetes.io/component: {{ include "ai-document-intelligence.receiptName" . }}
{{- end }}